version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
artifacts:
  files: 
    - Service.yml
