version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - ./mvnw install
  post_build:
    commands:
      #- docker build --tag "${REPOSITORY_URI}:${TAG}" .
      #- docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files: build.json
