version: 0.2
phases:
  pre_build: 
    commands: 
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - mvn package      
  post_build: 
    commands: 
      - printf '{"tag":"%s"}' $TAG > build.json
artifacts:
  files:
     - buildspec.yml
     - Service.yml
     - Dockerfile
     - target/gs-spring-boot-docker-0.1.0.jar
     - build.json
